schema_version = 1
schema_name = "naturalgrounding"

[[fields]]
key = "DB_BACKEND"
type = "str"
default = "postgres"
label = "DB Backend (postgres/mysql)"

[[fields]]
key = "DB_HOST"
type = "str"
default = "localhost"
label = "Database Host"

[[fields]]
key = "DB_PORT"
type = "port"
default = 5432
label = "Database Port"

[[fields]]
key = "DB_NAME"
type = "str"
default = "build"
label = "Database Name"

[[fields]]
key = "DB_USER"
type = "str"
default = "build"
label = "Database User"

[[fields]]
key = "DB_PW"
type = "str"
label = "Database Password"
required = true

[[fields]]
key = "VIDEOS_DIR"
type = "str"
default = "VIDEOS"
label = "Path to Video Directory"
